### ISSUE TITLE
Button that slide the sidebar

### ISSUE THREAD

**Issue by itaca9** [DH3ALEJANDRO/custom-work-for-brackets#101]
Hi, 

Is there any way to disable the:

> button (half circle) to the left half of the editor that slides the sidebar when it is closed

? 

I think it's a new update but for me it's really annoying, it appears even in non-distraction mode; when the sidebar is hidden I do not want it appearing. I've looked all the options and I have not found how to remove it, except for that I think it's a great app.

![thing](https://user-images.githubusercontent.com/33790647/32984124-4be8570a-cca0-11e7-9297-5f6a5a527297.jpg)

Thanks

**Comment by TruJared** [comment]
I would like to the ability to hide this as well. It is a bit distracting. Great work on this entire plugin though. I love it!!

**Comment by MasterReek** [comment]
I love this extension too.
How disable this button?
It's  too  stressful for us

**Comment by Mangatt** [comment]
Hi guys, I had similar problem, but it seems that developer is no longer mantaining this otherwise awesome extension. But there is quick fix for this behavior - locate extension folder:

1) Locate extension folder `%AppData%\Brackets\extensions\user\custom-work-for-brackets` (on Win10)
2) Now you have 2 options:
    - Option 1: Open file `sys\tabbar.html`, delete or comment out `<div class="cw-hover-sidebar" id="cw-{0}-hover-sidebar"></div>` and save
    - Option 2: Extract [tabbar.zip](https://github.com/DH3ALEJANDRO/custom-work-for-brackets/files/2180191/tabbar.zip) into `sys` folder and replace `tabbar.html` file
3) Reload Brackets

**And voilà! Annoying hover button is gone!**

**Comment by DH3ALEJANDRO** [comment]
I don't have any free time but these days I'll try to fix a lot of bugs.****

**Comment by DH3ALEJANDRO** [comment]
hi: install the new version available.
