### ISSUE TITLE
how to get rid of side file list

### ISSUE THREAD

**Issue by LukaszGrela** [DH3ALEJANDRO/custom-work-for-brackets#48]
Do you know how to turn off this side file list? It is redundant with your plugin and it "eats" space for the file tree list

![image](https://cloud.githubusercontent.com/assets/7643591/13103587/5f3fa7b2-d54f-11e5-95e6-904f67fb422f.png)

**Comment by LukaszGrela** [comment]
With some digging:)

`"custom.work.workingFilesSidebar": false,` in brackets.json

could you pull this setting out into the menu item? (under view option e.g. View->Show Working Files SIdebar)

**Comment by boatkung** [comment]
Navigate > Custom Work for Brackets Preferences
then uncheck workingFilesSidebar...

**Comment by DH3ALEJANDRO** [comment]
:unamused:.... :+1:

**Comment by LukaszGrela** [comment]
Can be closed, unless you can keep it open as a reminder to pull options into menu options?

**Comment by willprot** [comment]
This setting has no affect for me, I have ` "custom.work.workingFilesSidebar": false` but the sidebar remains open or reopens when I start Brackets

**Comment by DH3ALEJANDRO** [comment]
update `showWorkingFilesSidebar": false`

**Comment by willprot** [comment]
That wording is a little ambiguous, because it actually does hide the 'working files list'. but it does NOT hide the SideBar that contains the Working Files as it seems to describe.

I'd like the app to start with no sidebar visible at all, including the "Getting Started" and whatnot, instead of having to press "Ctrl-Alt-H" every time I start Brackets up.

**Comment by DH3ALEJANDRO** [comment]
try remove addon "no-Distraction mode"
