### ISSUE TITLE
White stripe on the right side of Brackets after Update

### ISSUE THREAD

**Issue by struchjuliankomma** [DH3ALEJANDRO/custom-work-for-brackets#88]
Hi,

since the last update i have a blank white space on the right side of my brackets
![brackets_problem](https://user-images.githubusercontent.com/29435284/27139597-bb6b344c-5123-11e7-974b-4d7c9e299129.jpg)
It appears after updating Costum Work. You know that problem?

**Comment by DH3ALEJANDRO** [comment]
please OS version

**Comment by vschaefer** [comment]
Hello,

I have the same problem.
Mac OS 10.12.5

**Comment by struchjuliankomma** [comment]
Sorry for not giving the information intentionally. i am working on Mac OS 10.12

**Comment by DH3ALEJANDRO** [comment]
I have tried the same system and there is no such problem, please list the extensions they use @struchjuliankomma @vschaefer

**Comment by struchjuliankomma** [comment]
Hi @DH3ALEJANDRO 
Here is a List of Extensions i am using (all are on their newest versions).

- Beautify (Drew Hamlett)
- Brackets Git (Martin Zagora)
- Brackets Outline List (Jan Pilzer)
- Custom work (Avril Alejandro)
- Duplicate Files&Folders (Torin Pascal)
- Extract for Brackets (Preview) (Adobe)
- FuncDocr (Ole Kröger)
- PHP SmartHints (Andrew McKenzie)
- SASSHints (Konstantin Kobs)
- SFtpUpload (Wang Yu)
- Show Whitespace (Dennis Kehrig)
- Todo (Mikael Jorhult)

**Comment by farcyde21** [comment]
I have the same issue. I disabling Custom Work fixed the issue (but of course made it less pretty). Note: If you currently have CW disabled, upon enabling it, you need to restart Brackets to see the change. My details: 
Win 7
Brackets Release 1.9 build 1.9.0-17312 (release 189f6d39a)
Custom Work 5.1.9

Without Custom Work:
![without cw](https://user-images.githubusercontent.com/2438222/27392742-6a83864a-5675-11e7-83ca-0d581e59753d.png)

With Custom Work:
![with cw](https://user-images.githubusercontent.com/2438222/27392746-6d947222-5675-11e7-845e-712d35eef088.png)

**Comment by DH3ALEJANDRO** [comment]
@struchjuliankomma @farcyde21 @vschaefer 

The error is caused by the following extension: "Brackets Outline List"
I tried to solve it but it is useless, maybe the author can do it

possible solutions:

 - Uncheck the "moveToolbarToSidebar" preference from "Custom Work"
 - Remove "Brackets Outline List"

**Comment by struchjuliankomma** [comment]
@DH3ALEJANDRO Thank you. Disable Brackets Outline List is a solution i can live with :)

**Comment by farcyde21** [comment]
It never worked for anything I was using Brackets for anyways. I'm also good with this solution.

**Comment by yougotwill** [comment]
Another solution is in the settings for Custom Work turn off moveToolbarToSideBar then you can keep Brackets Outline List and Custom work enabled.

![screen shot 2017-07-03 at 4 49 59 pm](https://user-images.githubusercontent.com/14887287/27797923-b79ca864-600f-11e7-82c4-8497ed37c2df.png)

**Comment by struchjuliankomma** [comment]
Thats what @DH3ALEJANDRO also suggested ;)

> possible solutions:

    Remove "Brackets Outline List"
    Uncheck the "moveToolbarToSidebar" preference from "Custom Work"

**Comment by gI7DUmmY** [comment]
Hi,
I tried your Brackets plugin and I grew attached to it (it's now one of my favorites).
Unfortunately, I deactivated it recently due to a strange black stripe at the bottom of brackets (between code and the default JSlint panel.
I tried various things I read above like unchecking everything in your plugin settings but no luck with that...

I'm working on Ubuntu 16.04LTS and Brackets 1.10.0-17483 (release 024bee940).
Here is a list of my other plugins :

- Brackets Git (Martin Zagora)
- Brackets Icons (Ivo Gabe)
- Lorem Ipsum (Lance Campbell)
- PHP SmartHints (Andrew MacKenzie)
- QuickDocsJS (Ole Kröger)
- Theseus for Brackets (Tom Lieber)

![brackets_ubuntu_01](https://user-images.githubusercontent.com/31273187/30416441-7c3c48fa-992c-11e7-8450-d814c8cd57ad.png)
Best regards.

**Comment by DH3ALEJANDRO** [comment]
*fixed, please update the Custom Work*

**Comment by gI7DUmmY** [comment]
Great work !
Thx

**Comment by rishikumar69** [comment]
Tried  both the trick but nothing worked 

Remove "Brackets Outline List"
Uncheck the "moveToolbarToSidebar" preference from "Custom Work"


![image](https://user-images.githubusercontent.com/3779634/30784282-0a8c6e3c-a170-11e7-9df7-2a7a58ede816.png)


Please help

**Comment by DH3ALEJANDRO** [comment]
@rishikumar69 according to the image, it does not appear that you have applied the solutions

**Comment by MiKr13** [comment]
You don't even need to disable or uninstall **Brackets Outline List**, all you need to do is sacrifice an option of moveToolbarToSidebar by unchecking it.
